# Default values for kaelly-rss.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

affinity: {}

configMap:
  METRIC_PORT: "2112"
  LOG_LEVEL: "info"
  PRODUCTION: "false"
  USER_AGENT: ""

secrets:
  MYSQL_URL: "localhost:3306"
  MYSQL_USER: ""
  MYSQL_PASSWORD: ""
  MYSQL_DATABASE: "kaellybot"
  RABBITMQ_ADDRESS: "amqp://localhost:5672"

cronjob:
  schedule: "0 0 * * *"
  name: "kaelly-rss"
  image:
    repository: ghcr.io/kaellybot/kaelly-rss
    tag: ""
  command: []
  args: []
  restartPolicy: "OnFailure"
  resources:
    limits:
      # cpu: 100m
      memory: 512Mi
    requests:
      # cpu: 100m
      memory: 128Mi